# Trigger of the pipeline
on:
  # initiate the pipeline when there is a push event in the main branch
  push:
    branches:
      - main

jobs:
  # Stage 1: Building the docker image
  build-docker-image:
    name: The job to build the application docker image
    # To define the machine that runs a job we use "runs-on"
    runs-on: csd-windows-local  # Using the self-hosted runner
    # The instructions are defined as steps
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2  # this is a GitHub action (pre-defined job)
                                   # that clones the project into the working directory

      - name: Build Docker Image
        run: docker build -t flask-app-1:v1.0.0 -f Dockerfile .

  deploy-docker-image:
    name: Deploy the flask image
    runs-on: csd-windows-local  # Using the self-hosted runner
    steps:
      - name: Deploy the image
        run: docker run -d -p 5000:5000 flask-app-1:v1.0.0  # -d tag allows us to run the container in the background

#  # Stage 2: Running the unit testing
#  unit-test:
#    name: The job to unittest the application
#    # To define the machine that runs a job we use "runs-on"
#    runs-on: ubuntu-latest
#    # The instructions are defined as steps
#    needs: [build-docker-image]  # Wait for the build-docker-image to finish, then it starts
#    steps:
#      - name: Echo unit testing of the application
#        run: echo "Unit test the docker image..."