jobs:
  # Stage 1: Building the docker image
  build-docker-image:
    name: The job to build the application docker image
    runs-on: aws-debian-runner-1  # Using the self-hosted runner
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2  # Clones the project into the working directory

      - name: Build Docker Image
        run: docker build -t flask-app-1:v1.0.0 -f Dockerfile .

  test:
    name: Unit testing of the application
    needs: [build-docker-image]
    runs-on: aws-debian-runner-1
    steps:
      - name: Clone and Checkout to the repository
        uses: actions/checkout@v2

      - name: Set up and run tests in a virtual environment
        shell: bash
        run: |
          # Create a virtual environment in a directory called venv
          python3 -m venv venv

          # Activate the virtual environment
          source venv/bin/activate

          # Upgrade pip and install dependencies
          pip install --upgrade pip
          pip install flask pytest

          # Run unit tests
          pytest tests/
