

# Trigger of the pipeline
on:
  # initiate the pipeline when there is a push event in the main branch
  push:
    branches:
      - main

jobs:
  # Stage 1: Building the docker image
  build-docker-image:
    name: The job to build the application docker image
    # To define the machine that runs a job we use "runs-on"
    runs-on: ubuntu-latest
    # The instructions are defined as steps
    steps:
      - name: Echo job
        run: echo "Building the docker image..."

  # Stage 2: Running the unit testing
  unit-test:
    name: The job to unittest the application
    # To define the machine that runs a job we use "runs-on"
    runs-on: ubuntu-latest
    # The instructions are defined as steps
    needs: [build-docker-image]  # Wait for the build-docker-image to finish, then it starts
    steps:
      - name: Echo unit testing of the application
        run: echo "Unit test the docker image..."